# Generated by Django 4.2.2 on 2023-06-30 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_code', models.CharField(max_length=8)),
                ('post_type', models.CharField(choices=[('DE', 'Declaration'), ('TH', 'Theory')], default='DE', max_length=2)),
                ('post_title', models.CharField(max_length=100)),
                ('post_desc', models.TextField()),
                ('post_author_name', models.CharField(max_length=20)),
                ('post_datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='date and time created')),
                ('post_number_of_messages', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_text', models.CharField(max_length=50)),
                ('tag_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
        ),
    ]
