# Generated by Django 4.2.2 on 2023-07-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='draft_code',
            field=models.CharField(default='d9sdjD3L', max_length=8),
            preserve_default=False,
        ),
    ]
