# Generated by Django 4.2.2 on 2023-07-19 16:49

from django.db import migrations
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_post_pen1_post_post_tpp_alter_post_post_author'),
    ]

    operations = [
    ]
