# Generated by Django 4.2.2 on 2023-07-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_post_number_of_no_votes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_timestamp',
            field=models.IntegerField(default=1689800049),
            preserve_default=False,
        ),
    ]
