# Generated by Django 4.2.2 on 2023-07-19 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_post_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_timestamp',
            new_name='post_timestamp_created',
        ),
    ]
