# Generated by Django 4.2.2 on 2023-08-27 06:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0015_alter_post_post_pen1_alter_post_post_tpp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='notified',
            field=models.ManyToManyField(blank=True, related_name='notified_field', to=settings.AUTH_USER_MODEL),
        ),
    ]
