# Generated by Django 4.2.2 on 2023-09-12 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0016_post_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='draft_type',
            field=models.CharField(choices=[('DE', 'Declaration'), ('TH', 'Theory'), ('QU', 'Question')], default='DE', max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='notified',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('DE', 'Declaration'), ('TH', 'Theory'), ('QU', 'Question')], default='DE', max_length=2),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_text',
            field=models.CharField(max_length=255),
        ),
    ]
