# Generated by Django 4.2.2 on 2023-11-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_alter_draft_draft_type_alter_post_notified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Splash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('splash_text', models.CharField()),
                ('splash_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
