# Generated by Django 4.2.2 on 2023-07-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='color',
            field=models.CharField(choices=[('OR', 'Orange'), ('BL', 'Blue'), ('GR', 'Green'), ('RE', 'Red'), ('PU', 'Purple'), ('PI', 'Pink'), ('MA', 'Maroon'), ('AQ', 'Aqua')], default='OR', max_length=2),
        ),
    ]
