# Generated by Django 4.2.2 on 2023-08-12 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='puppets',
            field=models.ManyToManyField(blank=True, related_name='puppets_field', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='watching',
            field=models.ManyToManyField(blank=True, related_name='watching_field', to=settings.AUTH_USER_MODEL),
        ),
    ]
