# Generated by Django 4.2.2 on 2023-10-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_watchlistactivity_watchlist_activity_type_ban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='color',
            field=models.CharField(choices=[('OR', 'Orange'), ('BL', 'Blue'), ('GR', 'Green'), ('RE', 'Red'), ('PU', 'Purple'), ('BR', 'Brown'), ('MA', 'Maroon'), ('DR', 'Dreadnought')], default='OR', max_length=2),
        ),
    ]
