# Generated by Django 4.2.2 on 2023-07-15 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_draft_draft_author_alter_post_post_author_vote'),
        ('users', '0002_user_watching_watchlist_activity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Watchlist_Activity',
            new_name='WatchlistActivity',
        ),
    ]
