# Generated by Django 4.2.2 on 2023-07-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_watchlist_activity_watchlistactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlistactivity',
            name='watchlist_activity_type',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DECLARE', 'Declare'), ('THEORISE', 'Theorise'), ('ENGAGE', 'Engage'), ('POPULAR', 'Popular'), ('INFAMOUS', 'Infamous'), ('CONTROVERSIAL', 'Controversial'), ('PEN1', 'Public Enemy Number 1'), ('TPP', 'The People Pleaser')], max_length=255),
        ),
    ]
