# Generated by Django 4.2.2 on 2023-07-17 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_watchlistactivity_watchlist_activity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_reporter_name', models.CharField(max_length=20)),
                ('report_reported_name', models.CharField(max_length=20)),
                ('report_reason', models.TextField()),
                ('report_datetime', models.DateTimeField(auto_now_add=True)),
                ('report_reported', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_reported', to=settings.AUTH_USER_MODEL)),
                ('report_reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_reporter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
