# Generated by Django 4.2.2 on 2023-06-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('datetime_sent', models.DateTimeField(auto_now_add=True, verbose_name='date and time sent')),
                ('author_name', models.CharField(max_length=20, verbose_name='display name of author')),
            ],
        ),
    ]
