# Generated by Django 4.2.2 on 2023-07-10 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('L', 'like'), ('D', 'dislike')], default='L', max_length=1)),
                ('interaction_datetime', models.DateTimeField(auto_now_add=True, verbose_name='date and time of the like')),
                ('interaction_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.message')),
                ('interaction_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
