# Generated by Django 4.2.2 on 2023-07-04 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_author_message_message_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='messagae_author_name',
            new_name='message_author_name',
        ),
    ]
