# Generated by Django 4.2.2 on 2023-07-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_messagae_author_name_message_message_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_code',
            field=models.CharField(default='j983jIUYT98H', unique=True, verbose_name=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='message_score',
            field=models.IntegerField(default=0),
        ),
    ]
