# Generated by Django 4.2.2 on 2023-07-10 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_interaction_interaction_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='interaction_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.message'),
        ),
    ]
