# Generated by Django 4.2.2 on 2023-07-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_interaction_interaction_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_code',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
