# Generated by Django 4.2.2 on 2023-10-29 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0013_alter_message_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_mentions',
            field=models.ManyToManyField(blank=True, related_name='message_mentions', to=settings.AUTH_USER_MODEL),
        ),
    ]
