# Generated by Django 4.2.2 on 2023-07-02 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_type', models.CharField(choices=[('DE', 'Declaration'), ('TH', 'Theory')], default='DE', max_length=2)),
                ('draft_title', models.CharField(max_length=100)),
                ('draft_desc', models.TextField()),
                ('draft_datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='date and time created')),
                ('draft_tags', models.CharField(max_length=200)),
                ('draft_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
