# Generated by Django 4.2.2 on 2023-07-21 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_tags',
        ),
    ]
